ls:
  .ts: kebab-case
  .tsx: kebab-case

  app/components:
    .tsx: regex:^[a-z0-9-]+(\.test)?$

  app/lib:
    .ts: regex:^[a-z0-9-]+(\.test)?$

  app/domain:
    .ts: regex:^[a-z0-9-]+\.(entity|vo|ds)(\.test)?$

  app/application:
    .ts: regex:^[a-z0-9-]+\.(usecase|repository\.interface)(\.test)?$

  app/infrastructure:
    .ts: regex:^[a-z0-9-]+\.(dto|mapper|repository)(\.test)?$

  app/presentation:
    .tsx: regex:^[a-z0-9-]+(\.(container|presentational))?(\.test)?$
    .ts: regex:^[a-z0-9-]+\.(hook|vd|vd-mapper)(\.test)?$

ignore:
  - .git
  - .github
  - .agents
  - .react-router
  - .vscode
  - node_modules
  - dist
  - build
  - coverage
